nelmio_api_doc:
    documentation:
        host: http://localhost:Applications/MAMP/htdocs/BileMo
        schemes: [http]
        info:
            title: BileMo
            description:
            version: 1.0.0
        security:
        - Bearer: []